pck_k = 4                               # pickup veichle dimension
dlv_k = 2                               # delivery veichle dimension
file_dir = "../istanze/"                 # folder containing istances
pck_file = "33p00p.tsp"                # pickup file
dlv_file = "33p00d.tsp"                # delivery file
to_round = true                         # round the value when find the euclidean dist
print_log = false                       # suppress logging of CPLEX
model_dump = true                       # for dumping to .lp file the model
save_dot = true                         # for saving the final matrices in dot file
result_name = "result.txt"              # filename used to write the instance solution
read_n_nodes = 10                        # max number of nodes to read from files
max_seconds = 40                       # max seconds to wait for a opt solution
out_name = "out.txt"                    # filename used to save the result of all the instances
#flavor of the problem
overlap = true                      
permutation = 1                     # 1: no permutation, 2: permutation, 3: pickup permutation, 4: delivery permutation
