pck_k = 6                               # pickup veichle dimension
dlv_k = 8                               # delivery veichle dimension
file_dir = "../istanze/"                 # folder containing istances
pck_file = "33p00p.tsp"                # pickup file
dlv_file = "33p00d.tsp"                # delivery file
to_round = true                         # round the value when find the euclidean dist
print_log = false                       # suppress logging of CPLEX
model_dump = true                       # for dumping to .lp file the model
save_dot = true                         # for saving the final matrices in dot file
result_name = "result.txt"              # filename used to write the results
read_n_node = 25                        # max number of nodes to read from files
max_seconds = 5                         # max seconds to wait for a opt solution
